### ISSUE TITLE
CloudCfg datasource and parser should leave full context in the filtered output

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2935]
The datasource should keep the full context of the keys collected so that the parser won't have to be changed in the future to add new sections of the configuration file.

The original file looks like this:
```
#cloud-config
users:
  - name: demo
    ssh-authorized-keys:
      - key_one
      - key_two
    passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/

network:
  config: disabled

system_info:
   default_user:
    name: user2
    plain_text_passwd: 'someP@assword'
    home: /home/user2
```

The datasource is filtering the file to limit the information collected, it is pulling the subkeys from the `network` section.  But in doing that it removes the context for those subkeys.  The better way to have accomplished that would be to keep the full context for the keys so instead of just this

`config: disabled`

It would keep this:

`network: {config: disabled}`

That way in the future if other information is collected from this same file that might have a `config` section, there won't be any ambiguity as to where `config` came from.
